/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  PayableOverrides,
} from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  EthForceSender,
  EthForceSenderInterface,
} from "../EthForceSender";

const _abi = [
  {
    inputs: [
      {
        internalType: "address payable",
        name: "recipient",
        type: "address",
      },
    ],
    stateMutability: "payable",
    type: "constructor",
  },
];

const _bytecode =
  "0x60806040526040516032380380603283398181016040526020811015602357600080fd5b50516001600160a01b038116fffe";

export class EthForceSender__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    recipient: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<EthForceSender> {
    return super.deploy(recipient, overrides || {}) as Promise<EthForceSender>;
  }
  getDeployTransaction(
    recipient: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(recipient, overrides || {});
  }
  attach(address: string): EthForceSender {
    return super.attach(address) as EthForceSender;
  }
  connect(signer: Signer): EthForceSender__factory {
    return super.connect(signer) as EthForceSender__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EthForceSenderInterface {
    return new utils.Interface(_abi) as EthForceSenderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EthForceSender {
    return new Contract(address, _abi, signerOrProvider) as EthForceSender;
  }
}
