/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface MockAssetTransfersHandlerInterface extends ethers.utils.Interface {
  functions: {
    "depositToInternalBalance(address,address,uint256)": FunctionFragment;
    "getInternalBalance(address,address)": FunctionFragment;
    "receiveAsset(address,uint256,address,bool)": FunctionFragment;
    "sendAsset(address,uint256,address,bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "depositToInternalBalance",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getInternalBalance",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveAsset",
    values: [string, BigNumberish, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "sendAsset",
    values: [string, BigNumberish, string, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositToInternalBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInternalBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sendAsset", data: BytesLike): Result;

  events: {};
}

export class MockAssetTransfersHandler extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MockAssetTransfersHandlerInterface;

  functions: {
    depositToInternalBalance(
      account: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getInternalBalance(
      account: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    receiveAsset(
      asset: string,
      amount: BigNumberish,
      sender: string,
      fromInternalBalance: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sendAsset(
      asset: string,
      amount: BigNumberish,
      recipient: string,
      toInternalBalance: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  depositToInternalBalance(
    account: string,
    token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getInternalBalance(
    account: string,
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  receiveAsset(
    asset: string,
    amount: BigNumberish,
    sender: string,
    fromInternalBalance: boolean,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sendAsset(
    asset: string,
    amount: BigNumberish,
    recipient: string,
    toInternalBalance: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    depositToInternalBalance(
      account: string,
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getInternalBalance(
      account: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    receiveAsset(
      asset: string,
      amount: BigNumberish,
      sender: string,
      fromInternalBalance: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    sendAsset(
      asset: string,
      amount: BigNumberish,
      recipient: string,
      toInternalBalance: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    depositToInternalBalance(
      account: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getInternalBalance(
      account: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    receiveAsset(
      asset: string,
      amount: BigNumberish,
      sender: string,
      fromInternalBalance: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sendAsset(
      asset: string,
      amount: BigNumberish,
      recipient: string,
      toInternalBalance: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    depositToInternalBalance(
      account: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getInternalBalance(
      account: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    receiveAsset(
      asset: string,
      amount: BigNumberish,
      sender: string,
      fromInternalBalance: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sendAsset(
      asset: string,
      amount: BigNumberish,
      recipient: string,
      toInternalBalance: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
